apiVersion: 1
groups:
  - orgId: 1
    name: DevOps App Alerts
    folder: DevOps
    interval: 1m
    rules:
      - uid: app-down-alert
        title: App Down Alert
        condition: C
        data:
          - refId: A
            queryType: ''
            relativeTimeRange: {from: 300, to: 0}
            datasourceUid: prometheus
            model:
              expr: up{job="devops-app"}
              intervalMs: 1000
              maxDataPoints: 43200
              refId: A
          - refId: C
            queryType: ''
            relativeTimeRange: {from: 0, to: 0}
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator: {params: [1], type: lt}
                  operator: {type: and}
                  query: {params: [A]}
                  reducer: {params: [], type: last}
                  type: query
              datasource: {type: __expr__, uid: __expr__}
              expression: A
              refId: C
              type: threshold
        noDataState: Alerting
        execErrState: Alerting
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: Application is DOWN
          description: devops-app is not responding

      - uid: high-memory-alert
        title: High Memory Usage
        condition: C
        data:
          - refId: A
            relativeTimeRange: {from: 300, to: 0}
            datasourceUid: prometheus
            model:
              expr: sum(jvm_memory_used_bytes{job="devops-app",area="heap"}) / sum(jvm_memory_max_bytes{job="devops-app",area="heap"})
              refId: A
          - refId: C
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator: {params: [0.85], type: gt}
                  query: {params: [A]}
                  reducer: {params: [], type: last}
                  type: query
              expression: A
              refId: C
              type: threshold
        noDataState: NoData
        execErrState: Error
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: High JVM Memory Usage
          description: JVM heap usage is above 85%
